In [1]:
import json
from pathlib import Path

data_path = Path("../Data/raw/acndata_sessions.json")

with open(data_path, "r", encoding="utf-8") as file:
    raw_data = json.load(file)

print(type(raw_data))

<class 'dict'>

In [2]:
print(raw_data.keys())

dict_keys(['_meta', '_items'])

In [3]:
sessions = raw_data["_items"]

print(type(sessions))
print("Number of sessions:", len(sessions))

<class 'list'>
Number of sessions: 10609

In [4]:
from pprint import pprint

pprint(sessions[0])

{'_id': '5c3fda9df9af8b0d99c6fd60',
 'clusterID': '0039',
 'connectionTime': 'Tue, 01 Jan 2019 03:45:49 GMT',
 'disconnectTime': 'Tue, 01 Jan 2019 17:57:23 GMT',
 'doneChargingTime': 'Tue, 01 Jan 2019 10:40:45 GMT',
 'kWhDelivered': 43.114,
 'sessionID': '2_39_138_29_2019-01-01 03:45:49.452098',
 'siteID': '0002',
 'spaceID': 'CA-304',
 'stationID': '2-39-138-29',
 'timezone': 'America/Los_Angeles',
 'userID': '000000489',
 'userInputs': [{'WhPerMile': 475,
                 'kWhRequested': 99.75,
                 'milesRequested': 210,
                 'minutesAvailable': 629,
                 'modifiedAt': 'Tue, 01 Jan 2019 03:47:45 GMT',
                 'paymentRequired': True,
                 'requestedDeparture': 'Tue, 01 Jan 2019 14:14:49 GMT',
                 'userID': 489},
                {'WhPerMile': 475,
                 'kWhRequested': 99.75,
                 'milesRequested': 210,
                 'minutesAvailable': 641,
                 'modifiedAt': 'Tue, 01 Jan 2019 03:50:27 GMT',
                 'paymentRequired': True,
                 'requestedDeparture': 'Tue, 01 Jan 2019 14:26:49 GMT',
                 'userID': 489}]}

In [5]:
print(sessions[0].keys())

dict_keys(['_id', 'clusterID', 'connectionTime', 'disconnectTime', 'doneChargingTime', 'kWhDelivered', 'sessionID', 'siteID', 'spaceID', 'stationID', 'timezone', 'userID', 'userInputs'])

In [6]:
from collections import Counter

field_counts = Counter()

for session in sessions:
    field_counts.update(session.keys())

for field, count in field_counts.items():
    print(f"{field}: {count}")

_id: 10609
clusterID: 10609
connectionTime: 10609
disconnectTime: 10609
doneChargingTime: 10609
kWhDelivered: 10609
sessionID: 10609
siteID: 10609
spaceID: 10609
stationID: 10609
timezone: 10609
userID: 10609
userInputs: 10609

In [7]:
import pandas as pd

df = pd.DataFrame(sessions)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (10609, 13)

,_id,clusterID,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,userInputs
0,5c3fda9df9af8b0d99c6fd60,0039,"Tue, 01 Jan 2019 03:45:49 GMT","Tue, 01 Jan 2019 17:57:23 GMT","Tue, 01 Jan 2019 10:40:45 GMT",43.114,2_39_138_29_2019-01-01 03:45:49.452098,0002,CA-304,2-39-138-29,America/Los_Angeles,000000489,"[{'WhPerMile': 475, 'kWhRequested': 99.75, 'mi..."
1,5c3fda9df9af8b0d99c6fd61,0039,"Tue, 01 Jan 2019 05:28:34 GMT","Tue, 01 Jan 2019 06:03:12 GMT","Tue, 01 Jan 2019 06:03:06 GMT",3.250,2_39_130_31_2019-01-01 05:28:33.527740,0002,CA-306,2-39-130-31,America/Los_Angeles,000001616,"[{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile..."
2,5c412c1df9af8b12cb56c27c,0039,"Tue, 01 Jan 2019 17:41:45 GMT","Tue, 01 Jan 2019 18:39:21 GMT","Tue, 01 Jan 2019 18:40:21 GMT",0.900,2_39_138_566_2019-01-01 17:41:44.784919,0002,CA-512,2-39-138-566,America/Los_Angeles,NaN,None
3,5c412c1df9af8b12cb56c27d,0039,"Tue, 01 Jan 2019 18:09:17 GMT","Wed, 02 Jan 2019 02:39:32 GMT","Tue, 01 Jan 2019 20:16:10 GMT",12.534,2_39_79_379_2019-01-01 18:09:16.991864,0002,CA-327,2-39-79-379,America/Los_Angeles,000000558,"[{'WhPerMile': 222, 'kWhRequested': 17.76, 'mi..."
4,5c412c1df9af8b12cb56c27e,0039,"Tue, 01 Jan 2019 18:39:25 GMT","Tue, 01 Jan 2019 19:18:49 GMT","Tue, 01 Jan 2019 19:19:47 GMT",0.883,2_39_138_566_2019-01-01 18:39:24.566872,0002,CA-512,2-39-138-566,America/Los_Angeles,NaN,None

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10609 entries, 0 to 10608
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               10609 non-null  str
 1   clusterID         10609 non-null  str
 2   connectionTime    10609 non-null  str
 3   disconnectTime    10609 non-null  str
 4   doneChargingTime  10143 non-null  str
 5   kWhDelivered      10609 non-null  float64
 6   sessionID         10609 non-null  str
 7   siteID            10609 non-null  str
 8   spaceID           10609 non-null  str
 9   stationID         10609 non-null  str
 10  timezone          10609 non-null  str
 11  userID            9067 non-null   str
 12  userInputs        9067 non-null   object
dtypes: float64(1), object(1), str(11)
memory usage: 3.1+ MB

In [9]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary

                  Missing Values  Missing Percentage
_id                            0                0.00
clusterID                      0                0.00
connectionTime                 0                0.00
disconnectTime                 0                0.00
doneChargingTime             466                4.39
kWhDelivered                   0                0.00
sessionID                      0                0.00
siteID                         0                0.00
spaceID                        0                0.00
stationID                      0                0.00
timezone                       0                0.00
userID                      1542               14.53
userInputs                  1542               14.53

In [10]:
print("Fully duplicated rows:", df.duplicated().sum())
print("Duplicate session IDs:", df["sessionID"].duplicated().sum())

TypeError: unhashable type: 'list'

In [11]:
print("Duplicate session IDs:", df["sessionID"].duplicated().sum())
print("Duplicate _id values:", df["_id"].duplicated().sum())

Duplicate session IDs: 0
Duplicate _id values: 0

In [12]:
print("Unique stations:", df["stationID"].nunique())
print("Unique spaces:", df["spaceID"].nunique())
print("Unique users:", df["userID"].nunique())
print("Total energy delivered:", round(df["kWhDelivered"].sum(), 2), "kWh")

Unique stations: 54
Unique spaces: 54
Unique users: 322
Total energy delivered: 94681.3 kWh

In [13]:
df["kWhDelivered"].describe()

count    10609.000000
mean         8.924621
std          9.161746
min          0.502000
25%          2.635000
50%          6.233000
75%         11.898000
max         75.528000
Name: kWhDelivered, dtype: float64

In [14]:
df["connectionTime"] = pd.to_datetime(df["connectionTime"], utc=True)
df["disconnectTime"] = pd.to_datetime(df["disconnectTime"], utc=True)
df["doneChargingTime"] = pd.to_datetime(df["doneChargingTime"], utc=True)

print("First connection:", df["connectionTime"].min())
print("Last connection:", df["connectionTime"].max())

First connection: 2019-01-01 03:45:49+00:00
Last connection: 2019-12-30 23:29:51+00:00

In [15]:
df["connectionTime_local"] = df["connectionTime"].dt.tz_convert("America/Los_Angeles")
df["disconnectTime_local"] = df["disconnectTime"].dt.tz_convert("America/Los_Angeles")
df["doneChargingTime_local"] = df["doneChargingTime"].dt.tz_convert("America/Los_Angeles")

print(df[["connectionTime", "connectionTime_local"]].head())

             connectionTime      connectionTime_local
0 2019-01-01 03:45:49+00:00 2018-12-31 19:45:49-08:00
1 2019-01-01 05:28:34+00:00 2018-12-31 21:28:34-08:00
2 2019-01-01 17:41:45+00:00 2019-01-01 09:41:45-08:00
3 2019-01-01 18:09:17+00:00 2019-01-01 10:09:17-08:00
4 2019-01-01 18:39:25+00:00 2019-01-01 10:39:25-08:00

In [16]:
df["connected_hours"] = (
    df["disconnectTime"] - df["connectionTime"]
).dt.total_seconds() / 3600

df["charging_hours"] = (
    df["doneChargingTime"] - df["connectionTime"]
).dt.total_seconds() / 3600

df[["kWhDelivered", "connected_hours", "charging_hours"]].describe()

       kWhDelivered  connected_hours  charging_hours
count  10609.000000     10609.000000    10143.000000
mean       8.924621         6.058171        2.890821
std        9.161746         5.790173        4.028832
min        0.502000         0.085278       -0.016667
25%        2.635000         2.368889        1.177917
50%        6.233000         5.817778        1.977778
75%       11.898000         8.584722        3.702639
max       75.528000       214.321944      200.015833

In [17]:
print("Negative charging durations:",
      (df["charging_hours"] < 0).sum())

print("Charging completion after disconnection:",
      (df["doneChargingTime"] > df["disconnectTime"]).sum())

print("Connected longer than 24 hours:",
      (df["connected_hours"] > 24).sum())

print("Charging longer than 24 hours:",
      (df["charging_hours"] > 24).sum())

Negative charging durations: 7
Charging completion after disconnection: 317
Connected longer than 24 hours: 77
Charging longer than 24 hours: 19

In [18]:
after_disconnect = df[df["doneChargingTime"] > df["disconnectTime"]].copy()

after_disconnect["difference_minutes"] = (
    after_disconnect["doneChargingTime"] - after_disconnect["disconnectTime"]
).dt.total_seconds() / 60

after_disconnect["difference_minutes"].describe()

count    317.000000
mean       1.126183
std        3.317140
min        0.016667
25%        0.966667
50%        0.983333
75%        0.983333
max       59.933333
Name: difference_minutes, dtype: float64

In [19]:
df.loc[
    df["charging_hours"] < 0,
    [
        "connectionTime",
        "doneChargingTime",
        "disconnectTime",
        "kWhDelivered",
        "stationID",
        "charging_hours"
    ]
]

,connectionTime,doneChargingTime,disconnectTime,kWhDelivered,stationID,charging_hours
2042,2019-03-05 19:13:55+00:00,2019-03-05 19:12:56+00:00,2019-03-05 22:50:39+00:00,0.706655,2-39-78-367,-0.016389
2076,2019-03-06 20:26:30+00:00,2019-03-06 20:25:34+00:00,2019-03-07 01:48:54+00:00,1.046381,2-39-78-367,-0.015556
3385,2019-04-15 20:24:13+00:00,2019-04-15 20:23:14+00:00,2019-04-15 23:39:04+00:00,0.635278,2-39-78-367,-0.016389
3409,2019-04-16 16:11:08+00:00,2019-04-16 16:10:11+00:00,2019-04-16 19:10:48+00:00,0.585977,2-39-78-367,-0.015833
7512,2019-09-04 16:35:04+00:00,2019-09-04 16:34:05+00:00,2019-09-05 00:44:27+00:00,1.584500,2-39-78-367,-0.016389
7563,2019-09-05 18:44:57+00:00,2019-09-05 18:43:57+00:00,2019-09-06 00:55:19+00:00,1.067230,2-39-78-360,-0.016667
9118,2019-10-29 17:22:32+00:00,2019-10-29 17:21:33+00:00,2019-10-31 01:57:20+00:00,6.316210,2-39-78-367,-0.016389

In [20]:
df.loc[
    df["connected_hours"] > 24,
    [
        "connectionTime",
        "disconnectTime",
        "kWhDelivered",
        "stationID",
        "connected_hours",
        "charging_hours"
    ]
].sort_values("connected_hours", ascending=False).head(10)

,connectionTime,disconnectTime,kWhDelivered,stationID,connected_hours,charging_hours
2828,2019-03-29 16:00:02+00:00,2019-04-07 14:19:21+00:00,13.198,2-39-91-437,214.321944,200.015833
6623,2019-08-02 15:51:22+00:00,2019-08-08 22:04:21+00:00,1.008,2-39-91-437,150.216389,150.232778
1063,2019-02-03 20:53:35+00:00,2019-02-09 17:50:05+00:00,14.162,2-39-123-23,140.941667,2.305556
4642,2019-05-23 16:18:45+00:00,2019-05-28 15:13:05+00:00,1.084,2-39-138-29,118.905556,76.575556
3280,2019-04-12 06:06:51+00:00,2019-04-17 02:20:31+00:00,1.056,2-39-127-19,116.227778,113.009722
4356,2019-05-15 06:05:07+00:00,2019-05-20 00:19:09+00:00,9.831,2-39-89-25,114.233889,1.585833
7993,2019-09-19 18:22:13+00:00,2019-09-24 02:42:24+00:00,5.806,2-39-79-380,104.336389,101.299722
2021,2019-03-05 16:27:42+00:00,2019-03-09 03:33:46+00:00,6.067,2-39-128-18,83.101111,2.011944
7881,2019-09-16 21:05:57+00:00,2019-09-20 02:10:38+00:00,10.621,2-39-92-436,77.078056,1.726111
5888,2019-07-08 00:11:53+00:00,2019-07-11 03:52:35+00:00,12.170,2-39-95-27,75.678333,42.625556